Fixing #53 #3, allows deleting tokens with backspaces when user has a custom keyboard
venmo/VENTokenField pull request #56
Opened 2015-03-17 00:26 UTC by frobichaud

2015-03-20 00:06 UTC, frobichaud commented
@ayanonagon, can you please review and merge this?

2015-03-23 17:38 UTC, ayanonagon commented on VENTokenField/VENTokenField.m
> +    BOOL isPressedBackspaceAfterSingleSpaceSymbol = [textField.text isEqualToString:@""] && range.location == 0 && range.length == 0 && string.length == 0;
`pressedBackspaceAfterSingleSpace` would be cleaner I think! :octocat:

2015-03-23 17:56 UTC, ayanonagon commented
1 tiny fix, then we can merge. Thank you for the pull-request! :balloon:

2017-07-13 14:58 UTC, StarWars commented on VENTokenField/VENTokenField.m
> +    BOOL isPressedBackspaceAfterSingleSpaceSymbol = [textField.text isEqualToString:@""] && range.location == 0 && range.length == 0 && string.length == 0;
@frobichaud It is not working with SwiftKey keyboard

2017-07-13 15:09 UTC, StarWars requested changes
The proposed solution doesn't work with the current version of SwiftKey keyboard.

2022-09-29 22:33 UTC, closed without merging